name = "PyJuliaProblems"
uuid = "a88bc313-3ac4-4629-8324-1ad5736289b6"
authors = ["Ingraham, Daniel James (GRC-LTV0) <daniel.j.ingraham@nasa.gov>"]
version = "0.1.0"

[deps]
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
